server:
  port: 8080

knife4j:
  enable: true
  openapi:
    title: aichat的api文档
    #    description: "`我是测试`,**你知道吗**
    #    # aaa"
    #    email: xiaoymin@foxmail.com
    #    concat: 八一菜刀
    #    url: https://docs.xiaominfo.com
    #    version: v4.0
    #    license: Apache 2.0
    #    license-url: https://stackoverflow.com/
    #    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: ai脑筋急转弯
        api-rule: package
        api-rule-resources:
          - com.hazergu.aichat.controller #这样knife4j就会到这个下面寻找接口

ai:
  apiKey: 97ced0ce-8e29-435f-a36b-2e00a3042334